apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinelx-prod

resources:
  - namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/ai-service-deployment.yaml
  - ../../base/analytics-service-deployment.yaml
  - ../../base/api-gateway-deployment.yaml
  - ../../base/assignment-service-deployment.yaml
  - ../../base/audit-service-deployment.yaml
  - ../../base/auth-service-deployment.yaml
  - ../../base/incident-service-deployment.yaml
  - ../../base/location-service-deployment.yaml
  - ../../base/notification-service-deployment.yaml
  - ../../base/realtime-service-deployment.yaml
  - ../../base/search-service-deployment.yaml
  - ../../base/sla-service-deployment.yaml
  - ../../base/ingress.yaml
  - ../../base/hpa.yaml
