apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelx-config
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres.sentinelx-prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis.sentinelx-prod.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.sentinelx-prod.svc.cluster.local:9092"
  OPENSEARCH_HOST: "opensearch.sentinelx-prod.svc.cluster.local"
  OPENSEARCH_PORT: "9200"
  QDRANT_HOST: "qdrant.sentinelx-prod.svc.cluster.local"
  QDRANT_PORT: "6333"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.sentinelx-prod.svc.cluster.local:4317"
