apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: OpenSearch
    type: opensearch
    access: proxy
    url: http://opensearch:9200
    isDefault: false
    jsonData:
      version: 2.12.0
      database: "sentinelx-incidents"
      timeField: "@timestamp"
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: "AdminPassword123!"
